spring:
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.79.155.125:3306/gmw?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10 # 最大等待连接中的数量，设为0则没有限制
      max-active: 50 # 最大连接活动数
      max-wait: 10000 # 最大等待毫秒数，单位为ms，超过时间会出错误信息
      initial-size: 5 # 数据库连接池初始化连接数
      default-transaction-isolation: 2 # 设置默认隔离级别为读写提交
  redis:
    database: 0 # redis数据库索引，默认为0
    host: 127.0.0.1
    port: 6379
    password: # 我没有设置密码
    lettuce:
      pool:
        max-idle: 20
        min-idle: 0
        max-active: 50
        max-wait: 2000ms # 使用负值表示没有限制
    timeout: 5000ms # 连接超时时间
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true # 是否启用mybatis全局二级缓存
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.edu.cqut.gmw.entity
  type-handlers-package: cn.edu.cqut.gmw.common.typehandler
logging:
  level:
    root: INFO
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG
    org.springframework.web: DEBUG
